### PR TITLE
Implement long-lived WASM exec in `hb_converge`, message caching during execution, and `dev_process` basics

### PR DESCRIPTION
**Pull request by samcamwilliams**

### CODE REVIEW

**Comment by twilson63** [comment]
Here is the results I am getting with this PR

```
gitpod /workspace/HyperBEAM (feat/dev_process) $ rebar3 eunit
===> Verifying dependencies...
make: Entering directory '/workspace/HyperBEAM'
make: Nothing to be done for 'wamr'.
make: Leaving directory '/workspace/HyperBEAM'
===> Analyzing applications...
===> Compiling hb
   ┌─ src/hb_store_fs.erl:
   │
 2 │  -behavior(hb_store).
   │   ╰── Warning: behaviour hb_store undefined


    ┌─ src/dev_scheduler.erl:
    │
 98 │          {false, _} ->
    │          ╰── Warning: this clause cannot match because of different types/sizes


    ┌─ src/hb_http_signature.erl:
    │
 30 │          <<SignatureComponentsLine/binary, <<"\n">>, <<"\"@signature-params\": ">>, SignatureParamsLine/binary>>,
    │          ╰── Warning: binary construction will fail because of a type mismatch

    ┌─ src/hb_http_signature.erl:
    │
 38 │      Key = maps:get(key, Authority),
    │      ╰── Warning: variable 'Key' is unused

    ┌─ src/hb_http_signature.erl:
    │
 38 │      Key = maps:get(key, Authority),
    │            ╰── Warning: the result of calling map_get/2 is ignored (suppress the warning by assigning the expression to the _ variable)

    ┌─ src/hb_http_signature.erl:
    │
 53 │              <<Line, I/binary, <<": ">>, V/binary, <<"\n">>>>
    │              ╰── Warning: binary construction will fail because of a type mismatch

     ┌─ src/hb_http_signature.erl:
     │
 138 │                      {field_not_found_error, <<"Component Identifier for a field MUST be present on the message">>};
     │                      ╰── Warning: a term is constructed, but never used

     ┌─ src/hb_http_signature.erl:
     │
 147 │                      {ok, {NormalizedItem, bin(Extracted)}}
     │                      ╰── Warning: a term is constructed, but never used

     ┌─ src/hb_http_signature.erl:
     │
 191 │                      {sf_key_not_found_error, <<"Component Identifier references key not found in dictionary structured field">>};
     │                      ╰── Warning: a term is constructed, but never used


     ┌─ src/hb_cache.erl:
     │
 323 │  lookup_message(Store, Path) ->
     │  ╰── Warning: function lookup_message/2 is unused

     ┌─ src/hb_cache.erl:
     │
 450 │  composite_unsigned_item_test_ignore() ->
     │  ╰── Warning: function composite_unsigned_item_test_ignore/0 is unused

     ┌─ src/hb_cache.erl:
     │
 472 │  composite_signed_item_test_ignore() ->
     │  ╰── Warning: function composite_signed_item_test_ignore/0 is unused


    ┌─ src/dev_scheduler_interface.erl:
    │
 22 │  info(M) ->
    │       ╰── Warning: variable 'M' is unused


     ┌─ src/hb_http_structured_fields.erl:
     │
 244 │  parse_struct_hd_test_() ->
     │  ╰── Warning: function parse_struct_hd_test_/0 is unused

     ┌─ src/hb_http_structured_fields.erl:
     │
 308 │  expected_to_term([Bare, []]) when
     │  ╰── Warning: function expected_to_term/1 is unused

     ┌─ src/hb_http_structured_fields.erl:
     │
 331 │  e2t(Dict = [[<<_/bits>>, _] | _]) ->
     │  ╰── Warning: function e2t/1 is unused

     ┌─ src/hb_http_structured_fields.erl:
     │
 341 │  e2tb(#{<<"__type">> := <<"token">>, <<"value">> := V}) ->
     │  ╰── Warning: function e2tb/1 is unused

     ┌─ src/hb_http_structured_fields.erl:
     │
 354 │  e2tp([]) ->
     │  ╰── Warning: function e2tp/1 is unused

     ┌─ src/hb_http_structured_fields.erl:
     │
 366 │  raw_to_binary(RawList) ->
     │  ╰── Warning: function raw_to_binary/1 is unused

     ┌─ src/hb_http_structured_fields.erl:
     │
 369 │  trim_ws(<<$\s, R/bits>>) -> trim_ws(R);
     │  ╰── Warning: function trim_ws/1 is unused

     ┌─ src/hb_http_structured_fields.erl:
     │
 372 │  trim_ws_end(_, -1) ->
     │  ╰── Warning: function trim_ws_end/2 is unused

     ┌─ src/hb_http_structured_fields.erl:
     │
 512 │  struct_hd_identity_test_() ->
     │  ╰── Warning: function struct_hd_identity_test_/0 is unused


     ┌─ src/hb_message.erl:
     │
 346 │  to_typed_keys({Key, Value}) ->
     │  ╰── Warning: function to_typed_keys/1 is unused

     ┌─ src/hb_message.erl:
     │
 348 │  to_typed_keys(Key, Value) when is_binary(Value) ->
     │  ╰── Warning: function to_typed_keys/2 is unused

     ┌─ src/hb_message.erl:
     │
 470 │      TX = #tx { unsigned_id = << 1:256 >>, last_tx = << 2:256 >> },
     │           ╰── Warning: a term is constructed, but never used

     ┌─ src/hb_message.erl:
     │
 538 │  txs_match(TX1, TX2) ->
     │  ╰── Warning: function txs_match/2 is unused

     ┌─ src/hb_message.erl:
     │
 723 │  signed_id_test_disabled() ->
     │  ╰── Warning: function signed_id_test_disabled/0 is unused


     ┌─ src/hb_converge.erl:
     │
 148 │  handle_resolved_result(Msg2List = [Status, Result|_], Msg2, Opts)
     │                                             ╰── Warning: variable 'Result' is unused

     ┌─ src/hb_converge.erl:
     │
 148 │  handle_resolved_result(Msg2List = [Status, Result|_], Msg2, Opts)
     │                                                        ╰── Warning: variable 'Msg2' is unused

     ┌─ src/hb_converge.erl:
     │
 148 │  handle_resolved_result(Msg2List = [Status, Result|_], Msg2, Opts)
     │                                                              ╰── Warning: variable 'Opts' is unused


Post-compile hooks executed
===> Performing EUnit tests...
======================== EUnit ========================
file "hb.app"
  application 'hb'
    module 'ar_bundles'
      ar_bundles: test_no_tags...[1.565 s] ok
      ar_bundles: test_with_tags...[0.536 s] ok
      ar_bundles: test_unsigned_data_item_id...ok
      ar_bundles: test_unsigned_data_item_normalization...ok
      ar_bundles: test_empty_bundle...[0.006 s] ok
      ar_bundles: test_bundle_with_one_item...ok
      ar_bundles: test_bundle_with_two_items...ok
      ar_bundles: test_recursive_bundle...[0.546 s] ok
      ar_bundles: test_bundle_map...[1.160 s] ok
      ar_bundles: test_basic_member_id...[1.256 s] ok
      ar_bundles: test_deep_member...[2.342 s] ok
      ar_bundles: test_serialize_deserialize_deep_signed_bundle...[1.724 s] ok
      ar_bundles: extremely_large_bundle_test...[3.683 s] ok
      [done in 12.857 s]
    module 'ar_deep_hash'
    module 'ar_timestamp'
    module 'ar_tx'
    module 'ar_wallet'
    module 'dev_cron'
    module 'dev_cu'
    module 'dev_dedup'
    module 'dev_json_iface'
    module 'dev_lookup'
    module 'dev_message'
      dev_message: get_keys_mod_test...ok
      dev_message: is_private_mod_test...[0.005 s] ok
      dev_message: keys_from_device_test...[0.002 s] ok
      dev_message: case_insensitive_get_test...ok
      dev_message: private_keys_are_filtered_test...[0.001 s] ok
      dev_message: cannot_get_private_keys_test...ok
      dev_message: key_from_device_test...ok
      dev_message: remove_test...[0.009 s] ok
      dev_message: set_conflicting_keys_test...[0.002 s] ok
      [done in 0.046 s]
    module 'dev_meta'
    module 'dev_monitor'
    module 'dev_mu'
    module 'dev_multipass'
    module 'dev_p4'
    module 'dev_poda'
    dev_process: schedule_on_process_test (module 'dev_process')...=INFO REPORT==== 9-Dec-2024::19:18:51.190027 ===
    alarm_handler: {set,{system_memory_high_watermark,[]}}
[1.985 s] ok
    module 'dev_scheduler'
      dev_scheduler: status_test...[0.002 s] ok
      dev_scheduler: register_new_process_test...[0.526 s] ok
      dev_scheduler: schedule_message_and_get_slot_test...[0.095 s] ok
      dev_scheduler: get_schedule_test...[0.191 s] ok
      [done in 0.826 s]
    module 'dev_scheduler_interface'
    module 'dev_scheduler_registry'
      dev_scheduler_registry: find_non_existent_process_test...ok
      dev_scheduler_registry: create_and_find_process_test...[0.001 s] ok
      dev_scheduler_registry: create_multiple_processes_test...[0.001 s] ok
      dev_scheduler_registry: get_all_processes_test...ok
      [done in 0.014 s]
    dev_scheduler_server: new_proc_test (module 'dev_scheduler_server')...[2.286 s] ok
    module 'dev_stack'
      dev_stack: transform_internal_call_device_test...[0.004 s] ok
      dev_stack: transform_external_call_device_test...[0.015 s] ok
      dev_stack: example_device_for_stack_test...[0.002 s] ok
      dev_stack: simple_stack_execute_test...[0.023 s] ok
      dev_stack: many_devices_test...[0.056 s] ok
      dev_stack: reinvocation_test...[0.052 s] ok
      dev_stack: skip_test...[0.013 s] ok
      [done in 0.186 s]
    dev_test: device_with_function_key_module_test (module 'dev_test')...[0.001 s] ok
    module 'dev_vfs'
    module 'dev_wasm'
    module 'hb'
    module 'hb_app'
    module 'hb_beamr'
      hb_beamr: nif_loads_test...ok
      hb_beamr: simple_wasm_test...[0.002 s] ok
      hb_beamr: simple_wasm_calling_test...[0.006 s] ok
      hb_beamr: imported_functions_are_called_test...[0.003 s] ok
      hb_beamr: wasm64_test...[0.001 s] ok
      hb_beamr: aos64_standalone_wex_test...[2.524 s] ok
      hb_beamr: checkpoint_and_resume_test...[3.087 s] ok
      [done in 5.644 s]
    module 'hb_beamr_io'
    module 'hb_cache'
      hb_cache: simple_path_resolution_test...[0.006 s] ok
      hb_cache: resursive_path_resolution_test...[0.006 s] ok
      hb_cache: hierarchical_path_resolution_test...[0.007 s] ok
      hb_cache: store_simple_unsigned_item_test...[0.007 s] ok
      hb_cache: simple_signed_item_test...[2.193 s] ok
      hb_cache: deeply_nested_item_test...[2.954 s] ok
      hb_cache: write_and_read_output_test...*timed out*
in function crypto:generate_key/3 (crypto.erl, line 2792)
in call from ar_wallet:new/1 (/workspace/HyperBEAM/src/ar_wallet.erl, line 19)
in call from hb_cache:create_signed_tx/1 (/workspace/HyperBEAM/src/hb_cache.erl, line 406)
in call from hb_cache:write_and_read_output_test/0 (/workspace/HyperBEAM/src/hb_cache.erl, line 521)
in call from eunit_test:'-mf_wrapper/2-fun-0-'/2 (eunit_test.erl, line 274)
in call from eunit_test:run_testfun/1 (eunit_test.erl, line 72)
in call from eunit_proc:run_test/1 (eunit_proc.erl, line 544)
in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 369)
in call from eunit_proc:handle_test/2 (eunit_proc.erl, line 527)
in call from eunit_proc:tests_inorder/3 (eunit_proc.erl, line 469)
in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 359)
in call from eunit_proc:run_group/2 (eunit_proc.erl, line 583)
in call from eunit_proc:tests_inorder/3 (eunit_proc.erl, line 469)
in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 359)
in call from eunit_proc:run_group/2 (eunit_proc.erl, line 583)
in call from eunit_proc:tests_inorder/3 (eunit_proc.erl, line 469)
in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 359)
in call from eunit_proc:run_group/2 (eunit_proc.erl, line 583)
in call from eunit_proc:tests_inorder/3 (eunit_proc.erl, line 469)
in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 359)
in call from eunit_proc:run_group/2 (eunit_proc.erl, line 583)
in call from eunit_proc:child_process/2 (eunit_proc.erl, line 387)
undefined
=======================================================
  Failed: 0.  Skipped: 0.  Passed: 53.
One or more tests were cancelled.
===> Error running tests
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
```


I am going to try a larger machine

**Comment by twilson63** [comment]
ok, with 16GB Memory and 8 Cores looks like all tests pass

```
gitpod /workspace/HyperBEAM (feat/dev_process) $ rebar3 eunit
===> Verifying dependencies...
make: Entering directory '/workspace/HyperBEAM'
make: Nothing to be done for 'wamr'.
make: Leaving directory '/workspace/HyperBEAM'
===> Analyzing applications...
===> Compiling hb
   ┌─ src/hb_store_fs.erl:
   │
 2 │  -behavior(hb_store).
   │   ╰── Warning: behaviour hb_store undefined


    ┌─ src/dev_scheduler.erl:
    │
 98 │          {false, _} ->
    │          ╰── Warning: this clause cannot match because of different types/sizes


    ┌─ src/hb_http_signature.erl:
    │
 30 │          <<SignatureComponentsLine/binary, <<"\n">>, <<"\"@signature-params\": ">>, SignatureParamsLine/binary>>,
    │          ╰── Warning: binary construction will fail because of a type mismatch

    ┌─ src/hb_http_signature.erl:
    │
 38 │      Key = maps:get(key, Authority),
    │      ╰── Warning: variable 'Key' is unused

    ┌─ src/hb_http_signature.erl:
    │
 38 │      Key = maps:get(key, Authority),
    │            ╰── Warning: the result of calling map_get/2 is ignored (suppress the warning by assigning the expression to the _ variable)

    ┌─ src/hb_http_signature.erl:
    │
 53 │              <<Line, I/binary, <<": ">>, V/binary, <<"\n">>>>
    │              ╰── Warning: binary construction will fail because of a type mismatch

     ┌─ src/hb_http_signature.erl:
     │
 138 │                      {field_not_found_error, <<"Component Identifier for a field MUST be present on the message">>};
     │                      ╰── Warning: a term is constructed, but never used

     ┌─ src/hb_http_signature.erl:
     │
 147 │                      {ok, {NormalizedItem, bin(Extracted)}}
     │                      ╰── Warning: a term is constructed, but never used

     ┌─ src/hb_http_signature.erl:
     │
 191 │                      {sf_key_not_found_error, <<"Component Identifier references key not found in dictionary structured field">>};
     │                      ╰── Warning: a term is constructed, but never used


     ┌─ src/hb_cache.erl:
     │
 323 │  lookup_message(Store, Path) ->
     │  ╰── Warning: function lookup_message/2 is unused

     ┌─ src/hb_cache.erl:
     │
 450 │  composite_unsigned_item_test_ignore() ->
     │  ╰── Warning: function composite_unsigned_item_test_ignore/0 is unused

     ┌─ src/hb_cache.erl:
     │
 472 │  composite_signed_item_test_ignore() ->
     │  ╰── Warning: function composite_signed_item_test_ignore/0 is unused


    ┌─ src/dev_scheduler_interface.erl:
    │
 22 │  info(M) ->
    │       ╰── Warning: variable 'M' is unused


     ┌─ src/hb_http_structured_fields.erl:
     │
 244 │  parse_struct_hd_test_() ->
     │  ╰── Warning: function parse_struct_hd_test_/0 is unused

     ┌─ src/hb_http_structured_fields.erl:
     │
 308 │  expected_to_term([Bare, []]) when
     │  ╰── Warning: function expected_to_term/1 is unused

     ┌─ src/hb_http_structured_fields.erl:
     │
 331 │  e2t(Dict = [[<<_/bits>>, _] | _]) ->
     │  ╰── Warning: function e2t/1 is unused

     ┌─ src/hb_http_structured_fields.erl:
     │
 341 │  e2tb(#{<<"__type">> := <<"token">>, <<"value">> := V}) ->
     │  ╰── Warning: function e2tb/1 is unused

     ┌─ src/hb_http_structured_fields.erl:
     │
 354 │  e2tp([]) ->
     │  ╰── Warning: function e2tp/1 is unused

     ┌─ src/hb_http_structured_fields.erl:
     │
 366 │  raw_to_binary(RawList) ->
     │  ╰── Warning: function raw_to_binary/1 is unused

     ┌─ src/hb_http_structured_fields.erl:
     │
 369 │  trim_ws(<<$\s, R/bits>>) -> trim_ws(R);
     │  ╰── Warning: function trim_ws/1 is unused

     ┌─ src/hb_http_structured_fields.erl:
     │
 372 │  trim_ws_end(_, -1) ->
     │  ╰── Warning: function trim_ws_end/2 is unused

     ┌─ src/hb_http_structured_fields.erl:
     │
 512 │  struct_hd_identity_test_() ->
     │  ╰── Warning: function struct_hd_identity_test_/0 is unused


     ┌─ src/hb_converge.erl:
     │
 148 │  handle_resolved_result(Msg2List = [Status, Result|_], Msg2, Opts)
     │                                             ╰── Warning: variable 'Result' is unused

     ┌─ src/hb_converge.erl:
     │
 148 │  handle_resolved_result(Msg2List = [Status, Result|_], Msg2, Opts)
     │                                                        ╰── Warning: variable 'Msg2' is unused

     ┌─ src/hb_converge.erl:
     │
 148 │  handle_resolved_result(Msg2List = [Status, Result|_], Msg2, Opts)
     │                                                              ╰── Warning: variable 'Opts' is unused


     ┌─ src/hb_message.erl:
     │
 346 │  to_typed_keys({Key, Value}) ->
     │  ╰── Warning: function to_typed_keys/1 is unused

     ┌─ src/hb_message.erl:
     │
 348 │  to_typed_keys(Key, Value) when is_binary(Value) ->
     │  ╰── Warning: function to_typed_keys/2 is unused

     ┌─ src/hb_message.erl:
     │
 470 │      TX = #tx { unsigned_id = << 1:256 >>, last_tx = << 2:256 >> },
     │           ╰── Warning: a term is constructed, but never used

     ┌─ src/hb_message.erl:
     │
 538 │  txs_match(TX1, TX2) ->
     │  ╰── Warning: function txs_match/2 is unused

     ┌─ src/hb_message.erl:
     │
 723 │  signed_id_test_disabled() ->
     │  ╰── Warning: function signed_id_test_disabled/0 is unused


Post-compile hooks executed
===> Performing EUnit tests...
======================== EUnit ========================
file "hb.app"
  application 'hb'
    module 'ar_bundles'
      ar_bundles: test_no_tags...[1.140 s] ok
      ar_bundles: test_with_tags...[0.718 s] ok
      ar_bundles: test_unsigned_data_item_id...ok
      ar_bundles: test_unsigned_data_item_normalization...ok
      ar_bundles: test_empty_bundle...[0.008 s] ok
      ar_bundles: test_bundle_with_one_item...ok
      ar_bundles: test_bundle_with_two_items...ok
      ar_bundles: test_recursive_bundle...[1.292 s] ok
      ar_bundles: test_bundle_map...[0.972 s] ok
      ar_bundles: test_basic_member_id...[2.278 s] ok
      ar_bundles: test_deep_member...[1.791 s] ok
      ar_bundles: test_serialize_deserialize_deep_signed_bundle...[3.259 s] ok
      ar_bundles: extremely_large_bundle_test...[3.331 s] ok
      [done in 14.828 s]
    module 'ar_deep_hash'
    module 'ar_timestamp'
    module 'ar_tx'
    module 'ar_wallet'
    module 'dev_cron'
    module 'dev_cu'
    module 'dev_dedup'
    module 'dev_json_iface'
    module 'dev_lookup'
    module 'dev_message'
      dev_message: get_keys_mod_test...ok
      dev_message: is_private_mod_test...[0.003 s] ok
      dev_message: keys_from_device_test...[0.002 s] ok
      dev_message: case_insensitive_get_test...ok
      dev_message: private_keys_are_filtered_test...[0.001 s] ok
      dev_message: cannot_get_private_keys_test...ok
      dev_message: key_from_device_test...ok
      dev_message: remove_test...[0.010 s] ok
      dev_message: set_conflicting_keys_test...[0.002 s] ok
      [done in 0.045 s]
    module 'dev_meta'
    module 'dev_monitor'
    module 'dev_mu'
    module 'dev_multipass'
    module 'dev_p4'
    module 'dev_poda'
    dev_process: schedule_on_process_test (module 'dev_process')...[1.919 s] ok
    module 'dev_scheduler'
      dev_scheduler: status_test...[0.003 s] ok
      dev_scheduler: register_new_process_test...[0.560 s] ok
      dev_scheduler: schedule_message_and_get_slot_test...[0.101 s] ok
      dev_scheduler: get_schedule_test...[0.165 s] ok
      [done in 0.841 s]
    module 'dev_scheduler_interface'
    module 'dev_scheduler_registry'
      dev_scheduler_registry: find_non_existent_process_test...ok
      dev_scheduler_registry: create_and_find_process_test...[0.001 s] ok
      dev_scheduler_registry: create_multiple_processes_test...[0.001 s] ok
      dev_scheduler_registry: get_all_processes_test...ok
      [done in 0.014 s]
    dev_scheduler_server: new_proc_test (module 'dev_scheduler_server')...[0.631 s] ok
    module 'dev_stack'
      dev_stack: transform_internal_call_device_test...[0.004 s] ok
      dev_stack: transform_external_call_device_test...[0.014 s] ok
      dev_stack: example_device_for_stack_test...[0.003 s] ok
      dev_stack: simple_stack_execute_test...[0.021 s] ok
      dev_stack: many_devices_test...[0.057 s] ok
      dev_stack: reinvocation_test...[0.040 s] ok
      dev_stack: skip_test...[0.010 s] ok
      [done in 0.172 s]
    dev_test: device_with_function_key_module_test (module 'dev_test')...[0.001 s] ok
    module 'dev_vfs'
    module 'dev_wasm'
    module 'hb'
    module 'hb_app'
    module 'hb_beamr'
      hb_beamr: nif_loads_test...ok
      hb_beamr: simple_wasm_test...[0.001 s] ok
      hb_beamr: simple_wasm_calling_test...[0.005 s] ok
      hb_beamr: imported_functions_are_called_test...[0.003 s] ok
      hb_beamr: wasm64_test...[0.001 s] ok
      hb_beamr: aos64_standalone_wex_test...[2.551 s] ok
      hb_beamr: checkpoint_and_resume_test...[3.081 s] ok
      [done in 5.663 s]
    module 'hb_beamr_io'
    module 'hb_cache'
      hb_cache: simple_path_resolution_test...[0.006 s] ok
      hb_cache: resursive_path_resolution_test...[0.006 s] ok
      hb_cache: hierarchical_path_resolution_test...[0.007 s] ok
      hb_cache: store_simple_unsigned_item_test...[0.007 s] ok
      hb_cache: simple_signed_item_test...[0.718 s] ok
      hb_cache: deeply_nested_item_test...[1.748 s] ok
      hb_cache: write_and_read_output_test...[4.154 s] ok
      hb_cache: latest_output_retrieval_test...[2.858 s] ok
      [done in 9.528 s]
    module 'hb_client'
    module 'hb_converge'
      hb_converge: key_from_id_device_test...[0.001 s] ok
      hb_converge: keys_from_id_device_test...ok
      hb_converge: path_test...[0.001 s] ok
      hb_converge: key_to_binary_test...ok
      hb_converge: resolve_binary_key_test...[0.001 s] ok
      hb_converge: key_from_id_device_with_args_test...[0.001 s] ok
      hb_converge: device_with_handler_function_test...ok
      hb_converge: device_with_default_handler_function_test...ok
      hb_converge: basic_get_test...[0.001 s] ok
      hb_converge: basic_set_test...[0.007 s] ok
      hb_converge: get_with_device_test...[0.001 s] ok
      hb_converge: get_as_with_device_test...[0.007 s] ok
      hb_converge: set_with_device_test...[0.013 s] ok
      hb_converge: deep_set_test...[0.023 s] ok
      hb_converge: deep_set_with_device_test...[0.026 s] ok
      hb_converge: device_exports_test...ok
      hb_converge: denormalized_device_key_test...[0.002 s] ok
      [done in 0.135 s]
    hb_crypto: sha256_chain_test (module 'hb_crypto')...ok
    module 'hb_http'
    module 'hb_http_router'
    module 'hb_http_signature'
    module 'hb_http_structured_fields'
    module 'hb_logger'
    module 'hb_message'
      hb_message: basic_map_to_tx_test...ok
      hb_message: default_tx_keys_removed_test...ok
      hb_message: minimization_test...ok
      hb_message: single_layer_message_to_tx_test...ok
      hb_message: single_layer_tx_to_message_test...ok
      hb_message: match_test...ok
      hb_message: structured_field_atom_parsing_test...ok
      hb_message: structured_field_decimal_parsing_test...ok
      hb_message: binary_to_binary_test...ok
      hb_message: message_with_large_keys_test...[0.001 s] ok
      hb_message: nested_message_with_large_keys_and_data_test...[0.001 s] ok
      hb_message: simple_nested_message_test...[0.001 s] ok
      hb_message: nested_message_with_large_data_test...[0.004 s] ok
      hb_message: deeply_nested_message_with_data_test...[0.003 s] ok
      hb_message: nested_structured_fields_test...[0.001 s] ok
      hb_message: nested_message_with_large_keys_test...[0.001 s] ok
      hb_message: signed_tx_to_message_and_back_test...[0.017 s] ok
      hb_message: signed_deep_tx_serialize_and_deserialize_test...[0.019 s] ok
      hb_message: calculate_unsigned_message_id_test...[0.001 s] ok
      hb_message: sign_serialize_deserialize_verify_test...[0.017 s] ok
      hb_message: unsigned_id_test...[0.001 s] ok
      [done in 0.130 s]
    module 'hb_metrics_collector'
    module 'hb_opts'
      hb_opts: global_get_test...[0.001 s] ok
      hb_opts: local_get_test...ok
      hb_opts: local_preference_test...ok
      hb_opts: global_preference_test...ok
      [done in 0.013 s]
    module 'hb_path'
      hb_path: push_hashpath_test...[0.001 s] ok
      hb_path: push_multiple_hashpaths_test...[0.001 s] ok
      hb_path: verify_hashpath_test...[0.003 s] ok
      hb_path: pop_from_message_test...ok
      hb_path: pop_from_path_list_test...ok
      hb_path: hd_test...ok
      hb_path: tl_test...ok
      [done in 0.026 s]
    module 'hb_private'
      hb_private: set_private_test...ok
      hb_private: get_private_key_test...[0.002 s] ok
      [done in 0.008 s]
    module 'hb_process'
    module 'hb_process_monitor'
    module 'hb_router'
    module 'hb_store'
    module 'hb_store_fs'
    module 'hb_store_remote_node'
    module 'hb_sup'
    module 'hb_test'
    module 'hb_util'
    module 'rsa_pss'
    module 'sec'
    module 'sec_helpers'
    module 'sec_tee'
    module 'sec_tpm'
    [done in 34.099 s]
  [done in 34.103 s]
=======================================================
  All 107 tests passed.
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
```

@oltarasenko let me know if you want me to merge this to help rebase your PR

**Comment by oltarasenko** [comment]
As I understand, it should still work even without it, but of course test improvements are welcome here :).

@twilson63 did you have a chance to re-run tests for the rocksdb pr after the rebar.config was fixed?

**Comment by twilson63** [comment]
I have been trying to keep up with the comments but could have missed the last one...

**Comment by samcamwilliams** [comment]
Hey @twilson63 @TillaTheHun0 and co,

This PR makes a number of significant changes such that `hb_converge` execution can be made long-running and is de-duplicated by default (multiple callers for the same result yield only one execution under-the-hood), as well as enabling cache write/lookup for (partial, if requested) results. This serves as a good foundation for long-running AO processes, but also allows us to make any computation we like long-lived, too. For example, if a user would like a serverless function to be hosted in the system, it is treated no differently than a normal AO execution.

The PR is now `+5,238 −2,520` lines and at this spot all 145 tests passes reliably. I am going to continue work from this branch on the execution and WASM flows of `dev_process` in `dev_process_exec`, but I recommend that we merge this so that everyone else is working on an up-to-date base for the repo.

One exception to using this as the new base might be @PeterFarber, whose BEAMR work might be affected by the `dev_wasm` import function reorg that I will be working on in the new branch. Will try to get those changes committed there as soon as I can, but plan to ensure the full 'CU' flow from `dev_process` is working, first.

**Comment by samcamwilliams** [comment]
BTW @PeterFarber @oltarasenko -- if you checkout `fca2c74a2a1a03a11f7ab358047bba19805371c4` I accidentally encountered a state where you can cause `beamr` to hang the Erlang VM. Not sure the cause and it wasn't on the critical path to debug it, but if you check it out and run `rebar3 eunit` you should be able to reproduce it.

I _think_ what was happening was something like:
1. WASM exec starts
2. Problem in an `import`
3. Start a new WASM(?)
4. -> ethr mutex lock failure

**Comment by twilson63** [comment]
if ready is it possible to post this PR into https://github.com/permaweb/HyperBEAM main branch?

**Review by twilson63 — APPROVED** [review]
All 145 Tests Pass, LGTM, is it possible we can get this PR to target permaweb/main ? or do you want to merge to samcamwilliams/main first then we create a PR from there to get to permaweb/main so everyone can work from it?

**Comment by samcamwilliams** [comment]
🤦‍♂️ @twilson63 . Sorry, multiple mains strikes again...

**Comment by PeterFarber** [comment]
> BTW @PeterFarber @oltarasenko -- if you checkout `fca2c74a2a1a03a11f7ab358047bba19805371c4` I accidentally encountered a state where you can cause `beamr` to hang the Erlang VM. Not sure the cause and it wasn't on the critical path to debug it, but if you check it out and run `rebar3 eunit` you should be able to reproduce it.
> 
> I _think_ what was happening was something like:
> 
> 1. WASM exec starts
> 2. Problem in an `import`
> 3. Start a new WASM(?)
> 4. -> ethr mutex lock failure

Will check it out

**Pull request merged**
