### PR TITLE
feat(ao_app): added attest_key func to use gotpm attest on 0 padded wallet addr

### PR DESCRIPTION
**Pull request by PeterFarber**

### CODE REVIEW

**Comment by twilson63** [comment]
@PeterFarber Looks like some conflicts to resolve, also, IDK, if this should exist in the `ao_app` module, maybe there is an `ao_tdx` module for this feature? @samcamwilliams WDYT?

**Comment by PeterFarber** [comment]
> @PeterFarber Looks like some conflicts to resolve, also, IDK, if this should exist in the `ao_app` module, maybe there is an `ao_tdx` module for this feature? @samcamwilliams WDYT?

Yeah we could move it to a separate module. 
Also we can just override what is already there, @samcamwilliams wrote what's in there as an example for me and left it in when he pushed.

**Comment by twilson63** [comment]
Maybe just resolve the conflicts then and we will look to get it merged

**Comment by PeterFarber** [comment]
> Maybe just resolve the conflicts then and we will look to get it merged

Resolved

**Pull request merged**
